wandb: Currently logged in as: yi-zhong. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.1
wandb: Run data is saved locally in /raid/home/yiso/working_directory/SeismicRepGAN-filippo/wandb/run-20231230_131506-8nw9zm8n
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fresh-salad-1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/yi-zhong/my-awesome-project
wandb: üöÄ View run at https://wandb.ai/yi-zhong/my-awesome-project/runs/8nw9zm8n
wandb: - 0.018 MB of 0.018 MB uploadedwandb:                                                                                
wandb: 
wandb: Run history:
wandb:  acc ‚ñÅ‚ñÜ‚ñà‚ñá‚ñÜ‚ñà‚ñá‚ñà
wandb: loss ‚ñà‚ñÜ‚ñÖ‚ñÇ‚ñÅ‚ñÅ‚ñÇ‚ñÅ
wandb: 
wandb: Run summary:
wandb:  acc 0.77999
wandb: loss 0.16016
wandb: 
wandb: üöÄ View run fresh-salad-1 at: https://wandb.ai/yi-zhong/my-awesome-project/runs/8nw9zm8n
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231230_131506-8nw9zm8n/logs
Traceback (most recent call last):
  File "/raid/home/yiso/working_directory/SeismicRepGAN-filippo/RepGAN_drive.py", line 121, in <module>
    # Load the dataset
  File "/raid/home/yiso/working_directory/SeismicRepGAN-filippo/RepGAN_drive.py", line 76, in Train
    #train_dataset, val_dataset = mdof.LoadData(**options)
  File "/raid/home/yiso/working_directory/SeismicRepGAN-filippo/RepGAN_utils.py", line 361, in DumpModels
    fidh5 = h5py.File(filepath,'w')
  File "/raid/home/yiso/.local/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/raid/home/yiso/.local/lib/python3.10/site-packages/h5py/_hl/files.py", line 241, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 122, in h5py.h5f.create
FileNotFoundError: [Errno 2] Unable to synchronously create file (unable to open file: name = 'dataset/results/Dx.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
